//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCertificador.Validador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoValidacion", Namespace="http://schemas.datacontract.org/2004/07/ServicioLocalContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteCertificador.Validador.Validacion[] DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteCertificador.Validador.ValidadorContract EntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteCertificador.Validador.Validacion[] Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteCertificador.Validador.ValidadorContract Entrada {
            get {
                return this.EntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntradaField, value) != true)) {
                    this.EntradaField = value;
                    this.RaisePropertyChanged("Entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido {
            get {
                return this.ValidoField;
            }
            set {
                if ((this.ValidoField.Equals(value) != true)) {
                    this.ValidoField = value;
                    this.RaisePropertyChanged("Valido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidadorContract", Namespace="http://schemas.datacontract.org/2004/07/ServicioLocalContract")]
    [System.SerializableAttribute()]
    public partial class ValidadorContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoAprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadenaOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadenaTimbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CertificadoNoFielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CertificadoValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTimbradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoAprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCertificadoSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelloValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumaConceptosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumaImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumaRetencionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoAprobacion {
            get {
                return this.AnoAprobacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoAprobacionField, value) != true)) {
                    this.AnoAprobacionField = value;
                    this.RaisePropertyChanged("AnoAprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadenaOriginal {
            get {
                return this.CadenaOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenaOriginalField, value) != true)) {
                    this.CadenaOriginalField = value;
                    this.RaisePropertyChanged("CadenaOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadenaTimbre {
            get {
                return this.CadenaTimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenaTimbreField, value) != true)) {
                    this.CadenaTimbreField = value;
                    this.RaisePropertyChanged("CadenaTimbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Certificado {
            get {
                return this.CertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadoField, value) != true)) {
                    this.CertificadoField = value;
                    this.RaisePropertyChanged("Certificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CertificadoNoFiel {
            get {
                return this.CertificadoNoFielField;
            }
            set {
                if ((this.CertificadoNoFielField.Equals(value) != true)) {
                    this.CertificadoNoFielField = value;
                    this.RaisePropertyChanged("CertificadoNoFiel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CertificadoValido {
            get {
                return this.CertificadoValidoField;
            }
            set {
                if ((this.CertificadoValidoField.Equals(value) != true)) {
                    this.CertificadoValidoField = value;
                    this.RaisePropertyChanged("CertificadoValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errores {
            get {
                return this.ErroresField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroresField, value) != true)) {
                    this.ErroresField = value;
                    this.RaisePropertyChanged("Errores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTimbrado {
            get {
                return this.FechaTimbradoField;
            }
            set {
                if ((this.FechaTimbradoField.Equals(value) != true)) {
                    this.FechaTimbradoField = value;
                    this.RaisePropertyChanged("FechaTimbrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoAprobacion {
            get {
                return this.NoAprobacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NoAprobacionField, value) != true)) {
                    this.NoAprobacionField = value;
                    this.RaisePropertyChanged("NoAprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCertificado {
            get {
                return this.NoCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoCertificadoField, value) != true)) {
                    this.NoCertificadoField = value;
                    this.RaisePropertyChanged("NoCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCertificadoSat {
            get {
                return this.NoCertificadoSatField;
            }
            set {
                if ((object.ReferenceEquals(this.NoCertificadoSatField, value) != true)) {
                    this.NoCertificadoSatField = value;
                    this.RaisePropertyChanged("NoCertificadoSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcEmisor {
            get {
                return this.RfcEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcEmisorField, value) != true)) {
                    this.RfcEmisorField = value;
                    this.RaisePropertyChanged("RfcEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sello {
            get {
                return this.SelloField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloField, value) != true)) {
                    this.SelloField = value;
                    this.RaisePropertyChanged("Sello");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelloSat {
            get {
                return this.SelloSatField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloSatField, value) != true)) {
                    this.SelloSatField = value;
                    this.RaisePropertyChanged("SelloSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SelloValido {
            get {
                return this.SelloValidoField;
            }
            set {
                if ((this.SelloValidoField.Equals(value) != true)) {
                    this.SelloValidoField = value;
                    this.RaisePropertyChanged("SelloValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumaConceptos {
            get {
                return this.SumaConceptosField;
            }
            set {
                if ((this.SumaConceptosField.Equals(value) != true)) {
                    this.SumaConceptosField = value;
                    this.RaisePropertyChanged("SumaConceptos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumaImpuestos {
            get {
                return this.SumaImpuestosField;
            }
            set {
                if ((this.SumaImpuestosField.Equals(value) != true)) {
                    this.SumaImpuestosField = value;
                    this.RaisePropertyChanged("SumaImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumaRetenciones {
            get {
                return this.SumaRetencionesField;
            }
            set {
                if ((this.SumaRetencionesField.Equals(value) != true)) {
                    this.SumaRetencionesField = value;
                    this.RaisePropertyChanged("SumaRetenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido {
            get {
                return this.ValidoField;
            }
            set {
                if ((this.ValidoField.Equals(value) != true)) {
                    this.ValidoField = value;
                    this.RaisePropertyChanged("Valido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlString {
            get {
                return this.XmlStringField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlStringField, value) != true)) {
                    this.XmlStringField = value;
                    this.RaisePropertyChanged("XmlString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Validacion", Namespace="http://schemas.datacontract.org/2004/07/ServicioLocalContract")]
    [System.SerializableAttribute()]
    public partial class Validacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido {
            get {
                return this.ValidoField;
            }
            set {
                if ((this.ValidoField.Equals(value) != true)) {
                    this.ValidoField = value;
                    this.RaisePropertyChanged("Valido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Validador.IServicioValidador")]
    public interface IServicioValidador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValidador/Validar", ReplyAction="http://tempuri.org/IServicioValidador/ValidarResponse")]
        ClienteCertificador.Validador.ResultadoValidacion Validar(string userName, string password, string comprobante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioValidadorChannel : ClienteCertificador.Validador.IServicioValidador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioValidadorClient : System.ServiceModel.ClientBase<ClienteCertificador.Validador.IServicioValidador>, ClienteCertificador.Validador.IServicioValidador {
        
        public ServicioValidadorClient() {
        }
        
        public ServicioValidadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioValidadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValidadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValidadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteCertificador.Validador.ResultadoValidacion Validar(string userName, string password, string comprobante) {
            return base.Channel.Validar(userName, password, comprobante);
        }
    }
}
