//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AddendaCoppel {
    
    private AddendaRequestForPayment requestForPaymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]

    public AddendaRequestForPayment requestForPayment {
        get {
            return this.requestForPaymentField;
        }
        set {
            this.requestForPaymentField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class AddendaRequestForPaymentSpecialInstruction
{

    private string[] textField;

    private string[] textField1;

    private AddendaRequestForPaymentSpecialInstructionCode codeField;

    /// <remarks/>
    [XmlElement("text")]
    public string[] text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [XmlText()]
    public string[] Text
    {
        get
        {
            return this.textField1;
        }
        set
        {
            this.textField1 = value;
        }
    }

    /// <remarks/>
    [XmlAttribute()]
    public AddendaRequestForPaymentSpecialInstructionCode code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]

public enum AddendaRequestForPaymentSpecialInstructionCode
{

    /// <remarks/>
    AAB,

    /// <remarks/>
    DUT,

    /// <remarks/>
    PUR,

    /// <remarks/>
    ZZZ,
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "requestForPayment")]
public partial class AddendaRequestForPayment {
    
    private AddendaRequestForPaymentRequestForPaymentIdentification requestForPaymentIdentificationField;
    
    private AddendaRequestForPaymentOrderIdentification orderIdentificationField;
    
    private AddendaRequestForPaymentSeller sellerField;
    
    private AddendaRequestForPaymentShipTo shipToField;
    
    private AddendaRequestForPaymentRegionCel regionCelField;
    
    private AddendaRequestForPaymentCustoms[] customsField;
    
    private AddendaRequestForPaymentCurrency[] currencyField;
    
    private AddendaRequestForPaymentCotizaOro cotizaOroField;
    
    private AddendaRequestForPaymentFleteCaja fleteCajaField;
    
    private AddendaRequestForPaymentAllowanceCharge[] allowanceChargeField;
    
    private AddendaRequestForPaymentLineItem[] lineItemField;
    
    private AddendaRequestForPaymentTotalCaractsFisicas totalCaractsFisicasField;
    
    private AddendaRequestForPaymentTotalAmount totalAmountField;
    
    private AddendaRequestForPaymentTotalAllowanceCharge[] totalAllowanceChargeField;
    
    private AddendaRequestForPaymentBaseAmount baseAmountField;
    
    private AddendaRequestForPaymentTax[] taxField;
    
    private AddendaRequestForPaymentPayableAmount payableAmountField;
    
    private AddendaRequestForPaymentCadenaOriginal cadenaOriginalField;
    
    private string typeField;
    
    private string contentVersionField;
    
    private string documentStructureVersionField;
    
    private AddendaRequestForPaymentDocumentStatus documentStatusField;
    
    private System.DateTime deliveryDateField;
    
    private bool deliveryDateFieldSpecified;

    private AddendaRequestForPaymentSpecialInstruction[] specialInstructionField;

    
    public AddendaRequestForPayment() {
        this.typeField = "SimpleInvoiceType";
        this.contentVersionField = "1.0";
        this.documentStructureVersionField = "CPLM1.0";
    }

    


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentRequestForPaymentIdentification requestForPaymentIdentification {
        get {
            return this.requestForPaymentIdentificationField;
        }
        set {
            this.requestForPaymentIdentificationField = value;
        }
    }
    [XmlElement("specialInstruction")]
    public AddendaRequestForPaymentSpecialInstruction[] specialInstruction
    {
        get
        {
            return this.specialInstructionField;
        }
        set
        {
            this.specialInstructionField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentOrderIdentification orderIdentification {
        get {
            return this.orderIdentificationField;
        }
        set {
            this.orderIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentSeller seller {
        get {
            return this.sellerField;
        }
        set {
            this.sellerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentShipTo shipTo {
        get {
            return this.shipToField;
        }
        set {
            this.shipToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentRegionCel RegionCel {
        get {
            return this.regionCelField;
        }
        set {
            this.regionCelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Customs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCustoms[] Customs {
        get {
            return this.customsField;
        }
        set {
            this.customsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("currency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCurrency[] currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCotizaOro CotizaOro {
        get {
            return this.cotizaOroField;
        }
        set {
            this.cotizaOroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentFleteCaja FleteCaja {
        get {
            return this.fleteCajaField;
        }
        set {
            this.fleteCajaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("allowanceCharge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentAllowanceCharge[] allowanceCharge {
        get {
            return this.allowanceChargeField;
        }
        set {
            this.allowanceChargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lineItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItem[] lineItem {
        get {
            return this.lineItemField;
        }
        set {
            this.lineItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTotalCaractsFisicas totalCaractsFisicas {
        get {
            return this.totalCaractsFisicasField;
        }
        set {
            this.totalCaractsFisicasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTotalAmount totalAmount {
        get {
            return this.totalAmountField;
        }
        set {
            this.totalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TotalAllowanceCharge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTotalAllowanceCharge[] TotalAllowanceCharge {
        get {
            return this.totalAllowanceChargeField;
        }
        set {
            this.totalAllowanceChargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentBaseAmount baseAmount {
        get {
            return this.baseAmountField;
        }
        set {
            this.baseAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTax[] tax {
        get {
            return this.taxField;
        }
        set {
            this.taxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentPayableAmount payableAmount {
        get {
            return this.payableAmountField;
        }
        set {
            this.payableAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCadenaOriginal cadenaOriginal {
        get {
            return this.cadenaOriginalField;
        }
        set {
            this.cadenaOriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentVersion {
        get {
            return this.contentVersionField;
        }
        set {
            this.contentVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string documentStructureVersion {
        get {
            return this.documentStructureVersionField;
        }
        set {
            this.documentStructureVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentDocumentStatus documentStatus {
        get {
            return this.documentStatusField;
        }
        set {
            this.documentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DeliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryDateSpecified {
        get {
            return this.deliveryDateFieldSpecified;
        }
        set {
            this.deliveryDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentRequestForPaymentIdentification {
    
    private AddendaRequestForPaymentRequestForPaymentIdentificationEntityType entityTypeField;
    
    private string uniqueCreatorIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentRequestForPaymentIdentificationEntityType entityType {
        get {
            return this.entityTypeField;
        }
        set {
            this.entityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string uniqueCreatorIdentification {
        get {
            return this.uniqueCreatorIdentificationField;
        }
        set {
            this.uniqueCreatorIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentRequestForPaymentIdentificationEntityType {
    
    /// <remarks/>
    INVOICE,
    
    /// <remarks/>
    DEBIT_NOTE,
    
    /// <remarks/>
    CREDIT_NOTE,
    
    /// <remarks/>
    LEASE_RECEIPT,
    
    /// <remarks/>
    HONORARY_RECEIPT,
    
    /// <remarks/>
    PARTIAL_INVOICE,
    
    /// <remarks/>
    TRANSPORT_DOCUMENT,
    
    /// <remarks/>
    AUTO_INVOICE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentOrderIdentification {
    
    private AddendaRequestForPaymentOrderIdentificationReferenceIdentification[] referenceIdentificationField;
    
    private System.DateTime referenceDateField;
    
    private System.DateTime fechaPromesaEntField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("referenceIdentification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentOrderIdentificationReferenceIdentification[] referenceIdentification {
        get {
            return this.referenceIdentificationField;
        }
        set {
            this.referenceIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime ReferenceDate {
        get {
            return this.referenceDateField;
        }
        set {
            this.referenceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FechaPromesaEnt {
        get {
            return this.fechaPromesaEntField;
        }
        set {
            this.fechaPromesaEntField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentOrderIdentificationReferenceIdentification {
    
    private AddendaRequestForPaymentOrderIdentificationReferenceIdentificationType typeField;
    
    private string valueField;
    
    public AddendaRequestForPaymentOrderIdentificationReferenceIdentification() {
        this.typeField = AddendaRequestForPaymentOrderIdentificationReferenceIdentificationType.ON;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentOrderIdentificationReferenceIdentificationType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentOrderIdentificationReferenceIdentificationType {
    
    /// <remarks/>
    ON,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentSeller {
    
    private string glnField;
    
    private AddendaRequestForPaymentSellerAlternatePartyIdentification alternatePartyIdentificationField;
    
    private string indentificaTipoProvField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gln {
        get {
            return this.glnField;
        }
        set {
            this.glnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentSellerAlternatePartyIdentification alternatePartyIdentification {
        get {
            return this.alternatePartyIdentificationField;
        }
        set {
            this.alternatePartyIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IndentificaTipoProv {
        get {
            return this.indentificaTipoProvField;
        }
        set {
            this.indentificaTipoProvField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentSellerAlternatePartyIdentification {
    
    private AddendaRequestForPaymentSellerAlternatePartyIdentificationType typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentSellerAlternatePartyIdentificationType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentSellerAlternatePartyIdentificationType {
    
    /// <remarks/>
    SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY,
    
    /// <remarks/>
    IEPS_REFERENCE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentShipTo {
    
    private string glnField;
    
    private AddendaRequestForPaymentShipToNameAndAddress nameAndAddressField;
    
    private string bodegaDestinoField;
    
    private string bodegaReceptoraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gln {
        get {
            return this.glnField;
        }
        set {
            this.glnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentShipToNameAndAddress nameAndAddress {
        get {
            return this.nameAndAddressField;
        }
        set {
            this.nameAndAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BodegaDestino {
        get {
            return this.bodegaDestinoField;
        }
        set {
            this.bodegaDestinoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BodegaReceptora {
        get {
            return this.bodegaReceptoraField;
        }
        set {
            this.bodegaReceptoraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentShipToNameAndAddress {
    
    private string[] nameField;
    
    private string[] streetAddressOneField;
    
    private string[] cityField;
    
    private string[] postalCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("streetAddressOne", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] streetAddressOne {
        get {
            return this.streetAddressOneField;
        }
        set {
            this.streetAddressOneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("city", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postalCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentRegionCel {
    
    private string regionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentCustoms {
    
    private AddendaRequestForPaymentCustomsAlternatePartyIdentification alternatePartyIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCustomsAlternatePartyIdentification alternatePartyIdentification {
        get {
            return this.alternatePartyIdentificationField;
        }
        set {
            this.alternatePartyIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentCustomsAlternatePartyIdentification {
    
    private AddendaRequestForPaymentCustomsAlternatePartyIdentificationType typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentCustomsAlternatePartyIdentificationType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentCustomsAlternatePartyIdentificationType {
    
    /// <remarks/>
    TN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentCurrency {
    
    private AddendaRequestForPaymentCurrencyCurrencyFunction[] currencyFunctionField;
    
    private decimal rateOfChangeField;
    
    private bool rateOfChangeFieldSpecified;
    
    private AddendaRequestForPaymentCurrencyCurrencyISOCode currencyISOCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("currencyFunction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentCurrencyCurrencyFunction[] currencyFunction {
        get {
            return this.currencyFunctionField;
        }
        set {
            this.currencyFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal rateOfChange {
        get {
            return this.rateOfChangeField;
        }
        set {
            this.rateOfChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rateOfChangeSpecified {
        get {
            return this.rateOfChangeFieldSpecified;
        }
        set {
            this.rateOfChangeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentCurrencyCurrencyISOCode currencyISOCode {
        get {
            return this.currencyISOCodeField;
        }
        set {
            this.currencyISOCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentCurrencyCurrencyFunction {
    
    /// <remarks/>
    BILLING_CURRENCY,
    
    /// <remarks/>
    PRICE_CURRENCY,
    
    /// <remarks/>
    PAYMENT_CURRENCY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentCurrencyCurrencyISOCode {
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    XEU,
    
    /// <remarks/>
    USD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentCotizaOro {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentFleteCaja {
    
    private AddendaRequestForPaymentFleteCajaType typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentFleteCajaType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentFleteCajaType {
    
    /// <remarks/>
    SELLER_PROVIDED,
    
    /// <remarks/>
    BUYER_PROVIDED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentAllowanceCharge {
    
    private AddendaRequestForPaymentAllowanceChargeSpecialServicesType specialServicesTypeField;
    
    private AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentage monetaryAmountOrPercentageField;
    
    private AddendaRequestForPaymentAllowanceChargeAllowanceChargeType allowanceChargeTypeField;
    
    private AddendaRequestForPaymentAllowanceChargeSettlementType settlementTypeField;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentAllowanceChargeSpecialServicesType specialServicesType {
        get {
            return this.specialServicesTypeField;
        }
        set {
            this.specialServicesTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentage monetaryAmountOrPercentage {
        get {
            return this.monetaryAmountOrPercentageField;
        }
        set {
            this.monetaryAmountOrPercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentAllowanceChargeAllowanceChargeType allowanceChargeType {
        get {
            return this.allowanceChargeTypeField;
        }
        set {
            this.allowanceChargeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentAllowanceChargeSettlementType settlementType {
        get {
            return this.settlementTypeField;
        }
        set {
            this.settlementTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentAllowanceChargeSpecialServicesType {
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    EAB,
    
    /// <remarks/>
    DXDIST,
    
    /// <remarks/>
    DXALM,
    
    /// <remarks/>
    DXECEN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentage {
    
    private AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRate rateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRate rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRate {
    
    private decimal percentageField;
    
    private AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRateBase baseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRateBase @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRateBase {
    
    /// <remarks/>
    INVOICE_VALUE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentAllowanceChargeAllowanceChargeType {
    
    /// <remarks/>
    ALLOWANCE_GLOBAL,
    
    /// <remarks/>
    CHARGE_GLOBAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentAllowanceChargeSettlementType {
    
    /// <remarks/>
    BILL_BACK,
    
    /// <remarks/>
    OFF_INVOICE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItem {
    
    private AddendaRequestForPaymentLineItemTradeItemIdentification tradeItemIdentificationField;
    
    private AddendaRequestForPaymentLineItemAlternateTradeItemIdentification[] alternateTradeItemIdentificationField;
    
    private AddendaRequestForPaymentLineItemTradeItemDescriptionInformation tradeItemDescriptionInformationField;
    
    private AddendaRequestForPaymentLineItemInvoicedQuantity invoicedQuantityField;
    
    private AddendaRequestForPaymentLineItemGrossPrice grossPriceField;
    
    private AddendaRequestForPaymentLineItemNetPrice netPriceField;
    
    private AddendaRequestForPaymentLineItemModeloInformation modeloInformationField;
    
    private AddendaRequestForPaymentLineItemLotNumber[] extendedAttributesField;
    
    private AddendaRequestForPaymentLineItemAllowanceCharge[] allowanceChargeField;
    
    private AddendaRequestForPaymentLineItemTotalLineAmount totalLineAmountField;
    
    private AddendaRequestForPaymentLineItemDetCaractsFisicas detCaractsFisicasField;
    
    private AddendaRequestForPaymentLineItemDetjoyeria detjoyeriaField;
    
    private AddendaRequestForPaymentLineItemPeso pesoField;
    
    private string typeField;
    
    private string numberField;
    
    public AddendaRequestForPaymentLineItem() {
        this.type = "SimpleInvoiceLineItemType";
        this.number = "1";

    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemTradeItemIdentification tradeItemIdentification {
        get {
            return this.tradeItemIdentificationField;
        }
        set {
            this.tradeItemIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("alternateTradeItemIdentification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemAlternateTradeItemIdentification[] alternateTradeItemIdentification {
        get {
            return this.alternateTradeItemIdentificationField;
        }
        set {
            this.alternateTradeItemIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemTradeItemDescriptionInformation tradeItemDescriptionInformation {
        get {
            return this.tradeItemDescriptionInformationField;
        }
        set {
            this.tradeItemDescriptionInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemInvoicedQuantity invoicedQuantity {
        get {
            return this.invoicedQuantityField;
        }
        set {
            this.invoicedQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemGrossPrice grossPrice {
        get {
            return this.grossPriceField;
        }
        set {
            this.grossPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemNetPrice netPrice {
        get {
            return this.netPriceField;
        }
        set {
            this.netPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemModeloInformation modeloInformation {
        get {
            return this.modeloInformationField;
        }
        set {
            this.modeloInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("lotNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public AddendaRequestForPaymentLineItemLotNumber[] extendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("allowanceCharge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemAllowanceCharge[] allowanceCharge {
        get {
            return this.allowanceChargeField;
        }
        set {
            this.allowanceChargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemTotalLineAmount totalLineAmount {
        get {
            return this.totalLineAmountField;
        }
        set {
            this.totalLineAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemDetCaractsFisicas DetCaractsFisicas {
        get {
            return this.detCaractsFisicasField;
        }
        set {
            this.detCaractsFisicasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemDetjoyeria Detjoyeria {
        get {
            return this.detjoyeriaField;
        }
        set {
            this.detjoyeriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemPeso Peso {
        get {
            return this.pesoField;
        }
        set {
            this.pesoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemTradeItemIdentification {
    
    private string gtinField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gtin {
        get {
            return this.gtinField;
        }
        set {
            this.gtinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemAlternateTradeItemIdentification {
    
    private AddendaRequestForPaymentLineItemAlternateTradeItemIdentificationType typeField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemAlternateTradeItemIdentificationType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemAlternateTradeItemIdentificationType {
    
    /// <remarks/>
    BUYER_ASSIGNED,
    
    /// <remarks/>
    SUPPLIER_ASSIGNED,
    
    /// <remarks/>
    SERIAL_NUMBER,
    
    /// <remarks/>
    GLOBAL_TRADE_ITEM_IDENTIFICATION,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemTradeItemDescriptionInformation {
    
    private string longTextField;
    
    private AddendaRequestForPaymentLineItemTradeItemDescriptionInformationLanguage languageField;
    
    private bool languageFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longText {
        get {
            return this.longTextField;
        }
        set {
            this.longTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemTradeItemDescriptionInformationLanguage language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool languageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemTradeItemDescriptionInformationLanguage {
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    EN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemInvoicedQuantity {
    
    private string unitOfMeasureField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemGrossPrice {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemNetPrice {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemModeloInformation {
    
    private string longTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longText {
        get {
            return this.longTextField;
        }
        set {
            this.longTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemLotNumber {
    
    private System.DateTime productionDateField;
    
    private bool productionDateFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime productionDate {
        get {
            return this.productionDateField;
        }
        set {
            this.productionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool productionDateSpecified {
        get {
            return this.productionDateFieldSpecified;
        }
        set {
            this.productionDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemAllowanceCharge {
    
    private AddendaRequestForPaymentLineItemAllowanceChargeSpecialServicesType specialServicesTypeField;
    
    private AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentage monetaryAmountOrPercentageField;
    
    private AddendaRequestForPaymentLineItemAllowanceChargeAllowanceChargeType allowanceChargeTypeField;
    
    private AddendaRequestForPaymentLineItemAllowanceChargeSettlementType settlementTypeField;
    
    private bool settlementTypeFieldSpecified;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemAllowanceChargeSpecialServicesType specialServicesType {
        get {
            return this.specialServicesTypeField;
        }
        set {
            this.specialServicesTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentage monetaryAmountOrPercentage {
        get {
            return this.monetaryAmountOrPercentageField;
        }
        set {
            this.monetaryAmountOrPercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemAllowanceChargeAllowanceChargeType allowanceChargeType {
        get {
            return this.allowanceChargeTypeField;
        }
        set {
            this.allowanceChargeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemAllowanceChargeSettlementType settlementType {
        get {
            return this.settlementTypeField;
        }
        set {
            this.settlementTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool settlementTypeSpecified {
        get {
            return this.settlementTypeFieldSpecified;
        }
        set {
            this.settlementTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemAllowanceChargeSpecialServicesType {
    
    /// <remarks/>
    PAD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentage {
    
    private string percentagePerUnitField;
    
    private AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentageRatePerUnit ratePerUnitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string percentagePerUnit {
        get {
            return this.percentagePerUnitField;
        }
        set {
            this.percentagePerUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentageRatePerUnit ratePerUnit {
        get {
            return this.ratePerUnitField;
        }
        set {
            this.ratePerUnitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentageRatePerUnit {
    
    private string amountPerUnitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string amountPerUnit {
        get {
            return this.amountPerUnitField;
        }
        set {
            this.amountPerUnitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemAllowanceChargeAllowanceChargeType {
    
    /// <remarks/>
    ALLOWANCE_GLOBAL,
    
    /// <remarks/>
    CHARGE_GLOBAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemAllowanceChargeSettlementType {
    
    /// <remarks/>
    OFF_INVOICE,
    
    /// <remarks/>
    CHARGE_TO_BE_PAID_BY_VENDOR,
    
    /// <remarks/>
    CHARGE_TO_BE_PAID_BY_CUSTOMER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemTotalLineAmount {
    
    private AddendaRequestForPaymentLineItemTotalLineAmountGrossAmount grossAmountField;
    
    private AddendaRequestForPaymentLineItemTotalLineAmountNetAmount netAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemTotalLineAmountGrossAmount grossAmount {
        get {
            return this.grossAmountField;
        }
        set {
            this.grossAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemTotalLineAmountNetAmount netAmount {
        get {
            return this.netAmountField;
        }
        set {
            this.netAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemTotalLineAmountGrossAmount {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemTotalLineAmountNetAmount {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemDetCaractsFisicas {
    
    private AddendaRequestForPaymentLineItemDetCaractsFisicasComposicion composicionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemDetCaractsFisicasComposicion Composicion {
        get {
            return this.composicionField;
        }
        set {
            this.composicionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemDetCaractsFisicasComposicion {
    
    private string materialField;
    
    private AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRelleno grmRellenoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRelleno GrmRelleno {
        get {
            return this.grmRellenoField;
        }
        set {
            this.grmRellenoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRelleno {
    
    private AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRellenoUdmedida udmedidaField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRellenoUdmedida Udmedida {
        get {
            return this.udmedidaField;
        }
        set {
            this.udmedidaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemDetCaractsFisicasComposicionGrmRellenoUdmedida {
    
    /// <remarks/>
    GRM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemDetjoyeria {
    
    private decimal kilatajeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Kilataje {
        get {
            return this.kilatajeField;
        }
        set {
            this.kilatajeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentLineItemPeso {
    
    private AddendaRequestForPaymentLineItemPesoUdmedida udmedidaField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentLineItemPesoUdmedida Udmedida {
        get {
            return this.udmedidaField;
        }
        set {
            this.udmedidaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentLineItemPesoUdmedida {
    
    /// <remarks/>
    GRM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentTotalCaractsFisicas {
    
    private AddendaRequestForPaymentTotalCaractsFisicasPeso pesoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTotalCaractsFisicasPeso Peso {
        get {
            return this.pesoField;
        }
        set {
            this.pesoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentTotalCaractsFisicasPeso {
    
    private AddendaRequestForPaymentTotalCaractsFisicasPesoUdmedida udmedidaField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentTotalCaractsFisicasPesoUdmedida Udmedida {
        get {
            return this.udmedidaField;
        }
        set {
            this.udmedidaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentTotalCaractsFisicasPesoUdmedida {
    
    /// <remarks/>
    GRM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentTotalAmount {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentTotalAllowanceCharge {
    
    private AddendaRequestForPaymentTotalAllowanceChargeSpecialServicesType specialServicesTypeField;
    
    private bool specialServicesTypeFieldSpecified;
    
    private decimal amountField;
    
    private bool amountFieldSpecified;
    
    private AddendaRequestForPaymentTotalAllowanceChargeAllowanceOrChargeType allowanceOrChargeTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTotalAllowanceChargeSpecialServicesType specialServicesType {
        get {
            return this.specialServicesTypeField;
        }
        set {
            this.specialServicesTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool specialServicesTypeSpecified {
        get {
            return this.specialServicesTypeFieldSpecified;
        }
        set {
            this.specialServicesTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmountSpecified {
        get {
            return this.amountFieldSpecified;
        }
        set {
            this.amountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentTotalAllowanceChargeAllowanceOrChargeType allowanceOrChargeType {
        get {
            return this.allowanceOrChargeTypeField;
        }
        set {
            this.allowanceOrChargeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentTotalAllowanceChargeSpecialServicesType {
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    ADS,
    
    /// <remarks/>
    ADO,
    
    /// <remarks/>
    ABZ,
    
    /// <remarks/>
    DA,
    
    /// <remarks/>
    EAA,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    TAE,
    
    /// <remarks/>
    SAB,
    
    /// <remarks/>
    RAA,
    
    /// <remarks/>
    PAD,
    
    /// <remarks/>
    FG,
    
    /// <remarks/>
    FA,
    
    /// <remarks/>
    TD,
    
    /// <remarks/>
    TS,
    
    /// <remarks/>
    TX,
    
    /// <remarks/>
    ZZZ,
    
    /// <remarks/>
    VAB,
    
    /// <remarks/>
    UM,
    
    /// <remarks/>
    DI,
    
    /// <remarks/>
    ADT,
    
    /// <remarks/>
    AJ,
    
    /// <remarks/>
    CAC,
    
    /// <remarks/>
    COD,
    
    /// <remarks/>
    EAB,
    
    /// <remarks/>
    FC,
    
    /// <remarks/>
    FI,
    
    /// <remarks/>
    HD,
    
    /// <remarks/>
    QD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentTotalAllowanceChargeAllowanceOrChargeType {
    
    /// <remarks/>
    ALLOWANCE,
    
    /// <remarks/>
    CHARGE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentBaseAmount {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentTax {
    
    private decimal taxPercentageField;
    
    private decimal taxAmountField;
    
    private AddendaRequestForPaymentTaxTaxCategory taxCategoryField;
    
    private AddendaRequestForPaymentTaxType typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal taxPercentage {
        get {
            return this.taxPercentageField;
        }
        set {
            this.taxPercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal taxAmount {
        get {
            return this.taxAmountField;
        }
        set {
            this.taxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AddendaRequestForPaymentTaxTaxCategory taxCategory {
        get {
            return this.taxCategoryField;
        }
        set {
            this.taxCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AddendaRequestForPaymentTaxType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentTaxTaxCategory {
    
    /// <remarks/>
    TRANSFERIDO,
    
    /// <remarks/>
    RETENIDO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentTaxType {
    
    /// <remarks/>
    GST,
    
    /// <remarks/>
    VAT,
    
    /// <remarks/>
    LAC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentPayableAmount {
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AddendaRequestForPaymentCadenaOriginal {
    
    private string cadenaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Cadena {
        get {
            return this.cadenaField;
        }
        set {
            this.cadenaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AddendaRequestForPaymentDocumentStatus {
    
    /// <remarks/>
    ORIGINAL,
    
    /// <remarks/>
    COPY,
    
    /// <remarks/>
    REEMPLAZA,
    
    /// <remarks/>
    DELETE,
}
