//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.CFDI.Cliente.Procesamiento.ServicioAutenticacionCFDI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAutenticacionCFDI.IAutenticacion")]
    public interface IAutenticacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/Autentica", ReplyAction="http://tempuri.org/IAutenticacion/AutenticaResponse")]
        string Autentica();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionChannel : SAT.CFDI.Cliente.Procesamiento.ServicioAutenticacionCFDI.IAutenticacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<SAT.CFDI.Cliente.Procesamiento.ServicioAutenticacionCFDI.IAutenticacion>, SAT.CFDI.Cliente.Procesamiento.ServicioAutenticacionCFDI.IAutenticacion {
        
        public AutenticacionClient() {
        }
        
        public AutenticacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Autentica() {
            return base.Channel.Autentica();
        }
    }
}
