//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


namespace ServicioLocal.Business
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pemex.com/facturaelectronica/addenda/v2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://pemex.com/facturaelectronica/addenda/v2", IsNullable = false, ElementName = "Addenda_Pemex")]
    public partial class AddendaPemex
    {

        private string cONTRATOField;

        private string o_SURTIMIENTOField;

        private string n_ESTIMACIONField;

        private string p_ESTIMACIONField;

        private string n_ACREEDORField;

        private string c_GESTORField;

        private string fINIQUITOField;

        private string pOSICIONAPField;

        private string aUTORIZAField;

        private string eNTRADAField;

        private string eJERCICIOField;

        private string cEJECUTORField;

        private string rECEPSAPField;

        private string nREMISIONField;

        private string pLAZOField;

        private string rFCPROVEEDORField;

        private string rEMESAField;

        private string vUREGIONField;

        private string fICHAEField;

        private string fICHAFField;

        private string mONEDAField;

        private string fONDOField;

        private string pOSICIONFField;

        private string cLAVE_TRANSPField;

        private string a_RELACIONField;

        private string iD_ANALITICOField;

        private string tIPO_PRODUCTOField;

        private string cEDULAField;

        private string cONTRATO_SIICField;

        private string oCOMERCIALField;

        private string sERVICIOGField;

        private string sERVICIOAField;

        private string cORREOPMIField;

        private string aNALITICOField;

        /// <remarks/>
        public string CONTRATO
        {
            get
            {
                return this.cONTRATOField;
            }
            set
            {
                this.cONTRATOField = value;
            }
        }

        /// <remarks/>
        public string O_SURTIMIENTO
        {
            get
            {
                return this.o_SURTIMIENTOField;
            }
            set
            {
                this.o_SURTIMIENTOField = value;
            }
        }

        /// <remarks/>
        public string N_ESTIMACION
        {
            get
            {
                return this.n_ESTIMACIONField;
            }
            set
            {
                this.n_ESTIMACIONField = value;
            }
        }

        /// <remarks/>
        public string P_ESTIMACION
        {
            get
            {
                return this.p_ESTIMACIONField;
            }
            set
            {
                this.p_ESTIMACIONField = value;
            }
        }

        /// <remarks/>
        public string N_ACREEDOR
        {
            get
            {
                return this.n_ACREEDORField;
            }
            set
            {
                this.n_ACREEDORField = value;
            }
        }

        /// <remarks/>
        public string C_GESTOR
        {
            get
            {
                return this.c_GESTORField;
            }
            set
            {
                this.c_GESTORField = value;
            }
        }

        /// <remarks/>
        public string FINIQUITO
        {
            get
            {
                return this.fINIQUITOField;
            }
            set
            {
                this.fINIQUITOField = value;
            }
        }

        /// <remarks/>
        public string POSICIONAP
        {
            get
            {
                return this.pOSICIONAPField;
            }
            set
            {
                this.pOSICIONAPField = value;
            }
        }

        /// <remarks/>
        public string AUTORIZA
        {
            get
            {
                return this.aUTORIZAField;
            }
            set
            {
                this.aUTORIZAField = value;
            }
        }

        /// <remarks/>
        public string ENTRADA
        {
            get
            {
                return this.eNTRADAField;
            }
            set
            {
                this.eNTRADAField = value;
            }
        }

        /// <remarks/>
        public string EJERCICIO
        {
            get
            {
                return this.eJERCICIOField;
            }
            set
            {
                this.eJERCICIOField = value;
            }
        }

        /// <remarks/>
        public string CEJECUTOR
        {
            get
            {
                return this.cEJECUTORField;
            }
            set
            {
                this.cEJECUTORField = value;
            }
        }

        /// <remarks/>
        public string RECEPSAP
        {
            get
            {
                return this.rECEPSAPField;
            }
            set
            {
                this.rECEPSAPField = value;
            }
        }

        /// <remarks/>
        public string NREMISION
        {
            get
            {
                return this.nREMISIONField;
            }
            set
            {
                this.nREMISIONField = value;
            }
        }

        /// <remarks/>
        public string PLAZO
        {
            get
            {
                return this.pLAZOField;
            }
            set
            {
                this.pLAZOField = value;
            }
        }

        /// <remarks/>
        public string RFCPROVEEDOR
        {
            get
            {
                return this.rFCPROVEEDORField;
            }
            set
            {
                this.rFCPROVEEDORField = value;
            }
        }

        /// <remarks/>
        public string REMESA
        {
            get
            {
                return this.rEMESAField;
            }
            set
            {
                this.rEMESAField = value;
            }
        }

        /// <remarks/>
        public string VUREGION
        {
            get
            {
                return this.vUREGIONField;
            }
            set
            {
                this.vUREGIONField = value;
            }
        }

        /// <remarks/>
        public string FICHAE
        {
            get
            {
                return this.fICHAEField;
            }
            set
            {
                this.fICHAEField = value;
            }
        }

        /// <remarks/>
        public string FICHAF
        {
            get
            {
                return this.fICHAFField;
            }
            set
            {
                this.fICHAFField = value;
            }
        }

        /// <remarks/>
        public string MONEDA
        {
            get
            {
                return this.mONEDAField;
            }
            set
            {
                this.mONEDAField = value;
            }
        }

        /// <remarks/>
        public string FONDO
        {
            get
            {
                return this.fONDOField;
            }
            set
            {
                this.fONDOField = value;
            }
        }

        /// <remarks/>
        public string POSICIONF
        {
            get
            {
                return this.pOSICIONFField;
            }
            set
            {
                this.pOSICIONFField = value;
            }
        }

        /// <remarks/>
        public string CLAVE_TRANSP
        {
            get
            {
                return this.cLAVE_TRANSPField;
            }
            set
            {
                this.cLAVE_TRANSPField = value;
            }
        }

        /// <remarks/>
        public string A_RELACION
        {
            get
            {
                return this.a_RELACIONField;
            }
            set
            {
                this.a_RELACIONField = value;
            }
        }

        /// <remarks/>
        public string ID_ANALITICO
        {
            get
            {
                return this.iD_ANALITICOField;
            }
            set
            {
                this.iD_ANALITICOField = value;
            }
        }

        /// <remarks/>
        public string TIPO_PRODUCTO
        {
            get
            {
                return this.tIPO_PRODUCTOField;
            }
            set
            {
                this.tIPO_PRODUCTOField = value;
            }
        }

        /// <remarks/>
        public string CEDULA
        {
            get
            {
                return this.cEDULAField;
            }
            set
            {
                this.cEDULAField = value;
            }
        }

        /// <remarks/>
        public string CONTRATO_SIIC
        {
            get
            {
                return this.cONTRATO_SIICField;
            }
            set
            {
                this.cONTRATO_SIICField = value;
            }
        }

        /// <remarks/>
        public string OCOMERCIAL
        {
            get
            {
                return this.oCOMERCIALField;
            }
            set
            {
                this.oCOMERCIALField = value;
            }
        }

        /// <remarks/>
        public string SERVICIOG
        {
            get
            {
                return this.sERVICIOGField;
            }
            set
            {
                this.sERVICIOGField = value;
            }
        }

        /// <remarks/>
        public string SERVICIOA
        {
            get
            {
                return this.sERVICIOAField;
            }
            set
            {
                this.sERVICIOAField = value;
            }
        }

        /// <remarks/>
        public string CORREOPMI
        {
            get
            {
                return this.cORREOPMIField;
            }
            set
            {
                this.cORREOPMIField = value;
            }
        }

        /// <remarks/>
        public string ANALITICO
        {
            get
            {
                return this.aNALITICOField;
            }
            set
            {
                this.aNALITICOField = value;
            }
        }
    }
}
