//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("AddendaBuzonFiscal", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class AddendaBuzonFiscalType {
    
    private EmisorType emisorField;
    
    private RemitenteType remitenteField;
    
    private ExpedidoEnType expedidoEnField;
    
    private ReceptorType receptorField;
    
    private DestinoType destinoField;
    
    private TipoDocumentoType tipoDocumentoField;
    
    private CFDType cFDField;
    
    private RetencionType[] retencionesField;
    
    private ExtraType[] extraField;
    
    private ExtraConceptosType[] extraConceptosField;
    
    private decimal versionField;
    
    public AddendaBuzonFiscalType() {
        this.versionField = ((decimal)(2.0m));
    }
    
    /// <remarks/>
    public EmisorType Emisor {
        get {
            return this.emisorField;
        }
        set {
            this.emisorField = value;
        }
    }
    
    /// <remarks/>
    public RemitenteType Remitente {
        get {
            return this.remitenteField;
        }
        set {
            this.remitenteField = value;
        }
    }
    
    /// <remarks/>
    public ExpedidoEnType ExpedidoEn {
        get {
            return this.expedidoEnField;
        }
        set {
            this.expedidoEnField = value;
        }
    }
    
    /// <remarks/>
    public ReceptorType Receptor {
        get {
            return this.receptorField;
        }
        set {
            this.receptorField = value;
        }
    }
    
    /// <remarks/>
    public DestinoType Destino {
        get {
            return this.destinoField;
        }
        set {
            this.destinoField = value;
        }
    }
    
    /// <remarks/>
    public TipoDocumentoType TipoDocumento {
        get {
            return this.tipoDocumentoField;
        }
        set {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public CFDType CFD {
        get {
            return this.cFDField;
        }
        set {
            this.cFDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable=false)]
    public RetencionType[] Retenciones {
        get {
            return this.retencionesField;
        }
        set {
            this.retencionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extra")]
    public ExtraType[] Extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtraConceptos")]
    public ExtraConceptosType[] ExtraConceptos {
        get {
            return this.extraConceptosField;
        }
        set {
            this.extraConceptosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Emisor", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class EmisorType {
    
    private string telefonoField;
    
    private string faxField;
    
    private string emailNotificacionesField;
    
    private string emailComercialField;
    
    private string webField;
    
    private string gLNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emailNotificaciones {
        get {
            return this.emailNotificacionesField;
        }
        set {
            this.emailNotificacionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emailComercial {
        get {
            return this.emailComercialField;
        }
        set {
            this.emailComercialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string web {
        get {
            return this.webField;
        }
        set {
            this.webField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GLN {
        get {
            return this.gLNField;
        }
        set {
            this.gLNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
public partial class t_InformacionAduanera {
    
    private string numeroField;
    
    private System.DateTime fechaField;
    
    private string aduanaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime fecha {
        get {
            return this.fechaField;
        }
        set {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aduana {
        get {
            return this.aduanaField;
        }
        set {
            this.aduanaField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DestinoType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemitenteType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
public partial class t_Ubicacion {
    
    private string calleField;
    
    private string numeroField;
    
    private string referenciaField;
    
    private string coloniaField;
    
    private string ciudadField;
    
    private string municipioField;
    
    private string estadoField;
    
    private string paisField;
    
    private string codigoPostalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string calle {
        get {
            return this.calleField;
        }
        set {
            this.calleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string referencia {
        get {
            return this.referenciaField;
        }
        set {
            this.referenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colonia {
        get {
            return this.coloniaField;
        }
        set {
            this.coloniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ciudad {
        get {
            return this.ciudadField;
        }
        set {
            this.ciudadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string municipio {
        get {
            return this.municipioField;
        }
        set {
            this.municipioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string estado {
        get {
            return this.estadoField;
        }
        set {
            this.estadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pais {
        get {
            return this.paisField;
        }
        set {
            this.paisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codigoPostal {
        get {
            return this.codigoPostalField;
        }
        set {
            this.codigoPostalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Remitente", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class RemitenteType : t_Ubicacion {
    
    private string claveIdentificacionField;
    
    private string rfcField;
    
    private string nombreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claveIdentificacion {
        get {
            return this.claveIdentificacionField;
        }
        set {
            this.claveIdentificacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc {
        get {
            return this.rfcField;
        }
        set {
            this.rfcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("ExpedidoEn", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class ExpedidoEnType {
    
    private string aliasField;
    
    private string telefonoField;
    
    private string faxField;
    
    private string emailField;
    
    private string gLNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GLN {
        get {
            return this.gLNField;
        }
        set {
            this.gLNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Receptor", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class ReceptorType {
    
    private string telefonoField;
    
    private string faxField;
    
    private string emailField;
    
    private string webField;
    
    private string nimField;
    
    private string gLNField;
    
    private string noClienteField;
    
    private string noProveedorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string web {
        get {
            return this.webField;
        }
        set {
            this.webField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nim {
        get {
            return this.nimField;
        }
        set {
            this.nimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GLN {
        get {
            return this.gLNField;
        }
        set {
            this.gLNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noCliente {
        get {
            return this.noClienteField;
        }
        set {
            this.noClienteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noProveedor {
        get {
            return this.noProveedorField;
        }
        set {
            this.noProveedorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Destino", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class DestinoType : t_Ubicacion {
    
    private string claveIdentificacionField;
    
    private string rfcField;
    
    private string nombreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claveIdentificacion {
        get {
            return this.claveIdentificacionField;
        }
        set {
            this.claveIdentificacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc {
        get {
            return this.rfcField;
        }
        set {
            this.rfcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("TipoDocumento", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class TipoDocumentoType {
    
    private NombreCortoType nombreCortoField;
    
    private DescripcionType descripcionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public NombreCortoType nombreCorto {
        get {
            return this.nombreCortoField;
        }
        set {
            this.nombreCortoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DescripcionType descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
public enum NombreCortoType {
    
    /// <remarks/>
    FAC,
    
    /// <remarks/>
    NCR,
    
    /// <remarks/>
    NCA,
    
    /// <remarks/>
    RHO,
    
    /// <remarks/>
    RAR,
    
    /// <remarks/>
    CPO,
    
    /// <remarks/>
    CSI,
    
    /// <remarks/>
    DDE,
    
    /// <remarks/>
    SP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
public enum DescripcionType {
    
    /// <remarks/>
    Factura,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Nota de Credito")]
    NotadeCredito,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Nota de Cargo")]
    NotadeCargo,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Recibo de Honorarios")]
    RecibodeHonorarios,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Recibo de Arrendamiento")]
    RecibodeArrendamiento,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Carta Porte")]
    CartaPorte,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Comprobante Simplificado")]
    ComprobanteSimplificado,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Donativo Deducible")]
    DonativoDeducible,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Estado de Cuenta")]
    EstadodeCuenta,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Comprobante Fiscal Digital para el Sector Primario")]
    ComprobanteFiscalDigitalparaelSectorPrimario,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("CFD", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class CFDType {
    
    private t_InformacionAduanera[] informacionAduaneraField;
    
    private bool vigenteField;
    
    private bool vigenteFieldSpecified;
    
    private System.DateTime fechaEnvioField;
    
    private bool fechaEnvioFieldSpecified;
    
    private System.DateTime fechaCancelacionField;
    
    private bool fechaCancelacionFieldSpecified;
    
    private System.DateTime fechaValidacionField;
    
    private bool fechaValidacionFieldSpecified;
    
    private bool validoField;
    
    private bool validoFieldSpecified;
    
    private string razonNoValidoField;
    
    private decimal porcentajeDescuentoField;
    
    private bool porcentajeDescuentoFieldSpecified;
    
    private string noOrdenField;
    
    private string compradorField;
    
    private string tipoMonedaField;
    
    private decimal tipoCambioField;
    
    private bool tipoCambioFieldSpecified;
    
    private System.DateTime fechaTipoCambioField;
    
    private bool fechaTipoCambioFieldSpecified;
    
    private string agenteVentasField;
    
    private string observacionesField;
    
    private string totalConLetraField;
    
    private string cargosField;
    
    private string refIDField;
    
    private string embarqueField;
    
    private string fobField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")]
    public t_InformacionAduanera[] InformacionAduanera {
        get {
            return this.informacionAduaneraField;
        }
        set {
            this.informacionAduaneraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool vigente {
        get {
            return this.vigenteField;
        }
        set {
            this.vigenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vigenteSpecified {
        get {
            return this.vigenteFieldSpecified;
        }
        set {
            this.vigenteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaEnvio {
        get {
            return this.fechaEnvioField;
        }
        set {
            this.fechaEnvioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaEnvioSpecified {
        get {
            return this.fechaEnvioFieldSpecified;
        }
        set {
            this.fechaEnvioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaCancelacion {
        get {
            return this.fechaCancelacionField;
        }
        set {
            this.fechaCancelacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaCancelacionSpecified {
        get {
            return this.fechaCancelacionFieldSpecified;
        }
        set {
            this.fechaCancelacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaValidacion {
        get {
            return this.fechaValidacionField;
        }
        set {
            this.fechaValidacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaValidacionSpecified {
        get {
            return this.fechaValidacionFieldSpecified;
        }
        set {
            this.fechaValidacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool valido {
        get {
            return this.validoField;
        }
        set {
            this.validoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validoSpecified {
        get {
            return this.validoFieldSpecified;
        }
        set {
            this.validoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string razonNoValido {
        get {
            return this.razonNoValidoField;
        }
        set {
            this.razonNoValidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal porcentajeDescuento {
        get {
            return this.porcentajeDescuentoField;
        }
        set {
            this.porcentajeDescuentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool porcentajeDescuentoSpecified {
        get {
            return this.porcentajeDescuentoFieldSpecified;
        }
        set {
            this.porcentajeDescuentoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noOrden {
        get {
            return this.noOrdenField;
        }
        set {
            this.noOrdenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comprador {
        get {
            return this.compradorField;
        }
        set {
            this.compradorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoMoneda {
        get {
            return this.tipoMonedaField;
        }
        set {
            this.tipoMonedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal tipoCambio {
        get {
            return this.tipoCambioField;
        }
        set {
            this.tipoCambioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tipoCambioSpecified {
        get {
            return this.tipoCambioFieldSpecified;
        }
        set {
            this.tipoCambioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaTipoCambio {
        get {
            return this.fechaTipoCambioField;
        }
        set {
            this.fechaTipoCambioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaTipoCambioSpecified {
        get {
            return this.fechaTipoCambioFieldSpecified;
        }
        set {
            this.fechaTipoCambioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string agenteVentas {
        get {
            return this.agenteVentasField;
        }
        set {
            this.agenteVentasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string observaciones {
        get {
            return this.observacionesField;
        }
        set {
            this.observacionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalConLetra {
        get {
            return this.totalConLetraField;
        }
        set {
            this.totalConLetraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cargos {
        get {
            return this.cargosField;
        }
        set {
            this.cargosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID {
        get {
            return this.refIDField;
        }
        set {
            this.refIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string embarque {
        get {
            return this.embarqueField;
        }
        set {
            this.embarqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fob {
        get {
            return this.fobField;
        }
        set {
            this.fobField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Retencion", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class RetencionType {
    
    private RetencionTypeImpuesto impuestoField;
    
    private decimal importeField;
    
    private decimal tasaField;
    
    public RetencionType() {
        this.tasaField = ((decimal)(10.00m));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RetencionTypeImpuesto impuesto {
        get {
            return this.impuestoField;
        }
        set {
            this.impuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal importe {
        get {
            return this.importeField;
        }
        set {
            this.importeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "10.00")]
    public decimal tasa {
        get {
            return this.tasaField;
        }
        set {
            this.tasaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
public enum RetencionTypeImpuesto {
    
    /// <remarks/>
    ISR,
    
    /// <remarks/>
    IVA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Extra", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class ExtraType {
    
    private string atributoField;
    
    private string valorField;
    
    private string prefijoField;
    
    private string sufijoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string atributo {
        get {
            return this.atributoField;
        }
        set {
            this.atributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valor {
        get {
            return this.valorField;
        }
        set {
            this.valorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefijo {
        get {
            return this.prefijoField;
        }
        set {
            this.prefijoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sufijo {
        get {
            return this.sufijoField;
        }
        set {
            this.sufijoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("ExtraConceptos", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class ExtraConceptosType {
    
    private string referencia1Field;
    
    private string referencia2Field;
    
    private string indicadorField;
    
    private string descripcionInglesField;
    
    private decimal numRemisionField;
    
    private bool numRemisionFieldSpecified;
    
    private decimal cargoField;
    
    private bool cargoFieldSpecified;
    
    private decimal descuentoField;
    
    private bool descuentoFieldSpecified;
    
    private string mensajeField;
    
    private decimal tasaImpuestoField;
    
    private bool tasaImpuestoFieldSpecified;
    
    private decimal impuestoField;
    
    private bool impuestoFieldSpecified;
    
    private decimal valorUnitarioMonedaExtranjeraField;
    
    private bool valorUnitarioMonedaExtranjeraFieldSpecified;
    
    private decimal importeMonedaExtranjeraField;
    
    private bool importeMonedaExtranjeraFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Referencia1 {
        get {
            return this.referencia1Field;
        }
        set {
            this.referencia1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Referencia2 {
        get {
            return this.referencia2Field;
        }
        set {
            this.referencia2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Indicador {
        get {
            return this.indicadorField;
        }
        set {
            this.indicadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descripcionIngles {
        get {
            return this.descripcionInglesField;
        }
        set {
            this.descripcionInglesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal numRemision {
        get {
            return this.numRemisionField;
        }
        set {
            this.numRemisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numRemisionSpecified {
        get {
            return this.numRemisionFieldSpecified;
        }
        set {
            this.numRemisionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cargoSpecified {
        get {
            return this.cargoFieldSpecified;
        }
        set {
            this.cargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal descuento {
        get {
            return this.descuentoField;
        }
        set {
            this.descuentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool descuentoSpecified {
        get {
            return this.descuentoFieldSpecified;
        }
        set {
            this.descuentoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mensaje {
        get {
            return this.mensajeField;
        }
        set {
            this.mensajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal tasaImpuesto {
        get {
            return this.tasaImpuestoField;
        }
        set {
            this.tasaImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tasaImpuestoSpecified {
        get {
            return this.tasaImpuestoFieldSpecified;
        }
        set {
            this.tasaImpuestoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal impuesto {
        get {
            return this.impuestoField;
        }
        set {
            this.impuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool impuestoSpecified {
        get {
            return this.impuestoFieldSpecified;
        }
        set {
            this.impuestoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal valorUnitarioMonedaExtranjera {
        get {
            return this.valorUnitarioMonedaExtranjeraField;
        }
        set {
            this.valorUnitarioMonedaExtranjeraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valorUnitarioMonedaExtranjeraSpecified {
        get {
            return this.valorUnitarioMonedaExtranjeraFieldSpecified;
        }
        set {
            this.valorUnitarioMonedaExtranjeraFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal importeMonedaExtranjera {
        get {
            return this.importeMonedaExtranjeraField;
        }
        set {
            this.importeMonedaExtranjeraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool importeMonedaExtranjeraSpecified {
        get {
            return this.importeMonedaExtranjeraFieldSpecified;
        }
        set {
            this.importeMonedaExtranjeraFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2")]
[System.Xml.Serialization.XmlRootAttribute("Retenciones", Namespace="http://www.buzonfiscal.com/ns/addenda/bf/2", IsNullable=false)]
public partial class RetencionesType {
    
    private RetencionType[] retencionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Retencion")]
    public RetencionType[] Retencion {
        get {
            return this.retencionField;
        }
        set {
            this.retencionField = value;
        }
    }
}
