//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/donat")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/donat", IsNullable = false)]
public partial class Donatarias
{

    private string versionField;

    private string noAutorizacionField;

    private System.DateTime fechaAutorizacionField;

    private string leyendaField;

    public Donatarias()
    {
        this.versionField = "1.1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noAutorizacion
    {
        get
        {
            return this.noAutorizacionField;
        }
        set
        {
            this.noAutorizacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime fechaAutorizacion
    {
        get
        {
            return this.fechaAutorizacionField;
        }
        set
        {
            this.fechaAutorizacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string leyenda
    {
        get
        {
            return this.leyendaField;
        }
        set
        {
            this.leyendaField = value;
        }
    }
}
