//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace I_RFC_SAT
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DescargasSatEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DescargasSatEntities usando la cadena de conexión encontrada en la sección 'DescargasSatEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DescargasSatEntities() : base("name=DescargasSatEntities", "DescargasSatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DescargasSatEntities.
        /// </summary>
        public DescargasSatEntities(string connectionString) : base(connectionString, "DescargasSatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DescargasSatEntities.
        /// </summary>
        public DescargasSatEntities(EntityConnection connection) : base(connection, "DescargasSatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<I_RFC_ACTUAL> I_RFC_ACTUAL
        {
            get
            {
                if ((_I_RFC_ACTUAL == null))
                {
                    _I_RFC_ACTUAL = base.CreateObjectSet<I_RFC_ACTUAL>("I_RFC_ACTUAL");
                }
                return _I_RFC_ACTUAL;
            }
        }
        private ObjectSet<I_RFC_ACTUAL> _I_RFC_ACTUAL;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<I_RFC0> I_RFC0
        {
            get
            {
                if ((_I_RFC0 == null))
                {
                    _I_RFC0 = base.CreateObjectSet<I_RFC0>("I_RFC0");
                }
                return _I_RFC0;
            }
        }
        private ObjectSet<I_RFC0> _I_RFC0;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<I_RFC1> I_RFC1
        {
            get
            {
                if ((_I_RFC1 == null))
                {
                    _I_RFC1 = base.CreateObjectSet<I_RFC1>("I_RFC1");
                }
                return _I_RFC1;
            }
        }
        private ObjectSet<I_RFC1> _I_RFC1;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LogI_RFC> LogI_RFC
        {
            get
            {
                if ((_LogI_RFC == null))
                {
                    _LogI_RFC = base.CreateObjectSet<LogI_RFC>("LogI_RFC");
                }
                return _LogI_RFC;
            }
        }
        private ObjectSet<LogI_RFC> _LogI_RFC;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vI_RFC> vI_RFC
        {
            get
            {
                if ((_vI_RFC == null))
                {
                    _vI_RFC = base.CreateObjectSet<vI_RFC>("vI_RFC");
                }
                return _vI_RFC;
            }
        }
        private ObjectSet<vI_RFC> _vI_RFC;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vI_RFC_Carga> vI_RFC_Carga
        {
            get
            {
                if ((_vI_RFC_Carga == null))
                {
                    _vI_RFC_Carga = base.CreateObjectSet<vI_RFC_Carga>("vI_RFC_Carga");
                }
                return _vI_RFC_Carga;
            }
        }
        private ObjectSet<vI_RFC_Carga> _vI_RFC_Carga;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LCO_ACTUAL> LCO_ACTUAL
        {
            get
            {
                if ((_LCO_ACTUAL == null))
                {
                    _LCO_ACTUAL = base.CreateObjectSet<LCO_ACTUAL>("LCO_ACTUAL");
                }
                return _LCO_ACTUAL;
            }
        }
        private ObjectSet<LCO_ACTUAL> _LCO_ACTUAL;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LCO0> LCO0
        {
            get
            {
                if ((_LCO0 == null))
                {
                    _LCO0 = base.CreateObjectSet<LCO0>("LCO0");
                }
                return _LCO0;
            }
        }
        private ObjectSet<LCO0> _LCO0;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LCO1> LCO1
        {
            get
            {
                if ((_LCO1 == null))
                {
                    _LCO1 = base.CreateObjectSet<LCO1>("LCO1");
                }
                return _LCO1;
            }
        }
        private ObjectSet<LCO1> _LCO1;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LogLCO> LogLCO
        {
            get
            {
                if ((_LogLCO == null))
                {
                    _LogLCO = base.CreateObjectSet<LogLCO>("LogLCO");
                }
                return _LogLCO;
            }
        }
        private ObjectSet<LogLCO> _LogLCO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vLCO> vLCO
        {
            get
            {
                if ((_vLCO == null))
                {
                    _vLCO = base.CreateObjectSet<vLCO>("vLCO");
                }
                return _vLCO;
            }
        }
        private ObjectSet<vLCO> _vLCO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vLCO_Carga> vLCO_Carga
        {
            get
            {
                if ((_vLCO_Carga == null))
                {
                    _vLCO_Carga = base.CreateObjectSet<vLCO_Carga>("vLCO_Carga");
                }
                return _vLCO_Carga;
            }
        }
        private ObjectSet<vLCO_Carga> _vLCO_Carga;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet I_RFC_ACTUAL. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToI_RFC_ACTUAL(I_RFC_ACTUAL i_RFC_ACTUAL)
        {
            base.AddObject("I_RFC_ACTUAL", i_RFC_ACTUAL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet I_RFC0. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToI_RFC0(I_RFC0 i_RFC0)
        {
            base.AddObject("I_RFC0", i_RFC0);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet I_RFC1. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToI_RFC1(I_RFC1 i_RFC1)
        {
            base.AddObject("I_RFC1", i_RFC1);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LogI_RFC. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLogI_RFC(LogI_RFC logI_RFC)
        {
            base.AddObject("LogI_RFC", logI_RFC);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vI_RFC. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovI_RFC(vI_RFC vI_RFC)
        {
            base.AddObject("vI_RFC", vI_RFC);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vI_RFC_Carga. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovI_RFC_Carga(vI_RFC_Carga vI_RFC_Carga)
        {
            base.AddObject("vI_RFC_Carga", vI_RFC_Carga);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LCO_ACTUAL. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLCO_ACTUAL(LCO_ACTUAL lCO_ACTUAL)
        {
            base.AddObject("LCO_ACTUAL", lCO_ACTUAL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LCO0. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLCO0(LCO0 lCO0)
        {
            base.AddObject("LCO0", lCO0);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LCO1. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLCO1(LCO1 lCO1)
        {
            base.AddObject("LCO1", lCO1);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LogLCO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLogLCO(LogLCO logLCO)
        {
            base.AddObject("LogLCO", logLCO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vLCO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovLCO(vLCO vLCO)
        {
            base.AddObject("vLCO", vLCO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vLCO_Carga. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovLCO_Carga(vLCO_Carga vLCO_Carga)
        {
            base.AddObject("vLCO_Carga", vLCO_Carga);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="I_RFC_ACTUAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class I_RFC_ACTUAL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto I_RFC_ACTUAL.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static I_RFC_ACTUAL CreateI_RFC_ACTUAL(global::System.Int32 id)
        {
            I_RFC_ACTUAL i_RFC_ACTUAL = new I_RFC_ACTUAL();
            i_RFC_ACTUAL.ID = id;
            return i_RFC_ACTUAL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaUltimaActualizacion
        {
            get
            {
                return _FechaUltimaActualizacion;
            }
            set
            {
                OnFechaUltimaActualizacionChanging(value);
                ReportPropertyChanging("FechaUltimaActualizacion");
                _FechaUltimaActualizacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaUltimaActualizacion");
                OnFechaUltimaActualizacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaUltimaActualizacion;
        partial void OnFechaUltimaActualizacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaUltimaActualizacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreTabla
        {
            get
            {
                return _NombreTabla;
            }
            set
            {
                OnNombreTablaChanging(value);
                ReportPropertyChanging("NombreTabla");
                _NombreTabla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreTabla");
                OnNombreTablaChanged();
            }
        }
        private global::System.String _NombreTabla;
        partial void OnNombreTablaChanging(global::System.String value);
        partial void OnNombreTablaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="I_RFC0")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class I_RFC0 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto I_RFC0.
        /// </summary>
        /// <param name="rFC">Valor inicial de la propiedad RFC.</param>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static I_RFC0 CreateI_RFC0(global::System.String rFC, global::System.Int64 id)
        {
            I_RFC0 i_RFC0 = new I_RFC0();
            i_RFC0.RFC = rFC;
            i_RFC0.ID = id;
            return i_RFC0;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RFC
        {
            get
            {
                return _RFC;
            }
            set
            {
                OnRFCChanging(value);
                ReportPropertyChanging("RFC");
                _RFC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RFC");
                OnRFCChanged();
            }
        }
        private global::System.String _RFC;
        partial void OnRFCChanging(global::System.String value);
        partial void OnRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SNCF
        {
            get
            {
                return _SNCF;
            }
            set
            {
                OnSNCFChanging(value);
                ReportPropertyChanging("SNCF");
                _SNCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SNCF");
                OnSNCFChanged();
            }
        }
        private global::System.String _SNCF;
        partial void OnSNCFChanging(global::System.String value);
        partial void OnSNCFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUBCONTRATACION
        {
            get
            {
                return _SUBCONTRATACION;
            }
            set
            {
                OnSUBCONTRATACIONChanging(value);
                ReportPropertyChanging("SUBCONTRATACION");
                _SUBCONTRATACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUBCONTRATACION");
                OnSUBCONTRATACIONChanged();
            }
        }
        private global::System.String _SUBCONTRATACION;
        partial void OnSUBCONTRATACIONChanging(global::System.String value);
        partial void OnSUBCONTRATACIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="I_RFC1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class I_RFC1 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto I_RFC1.
        /// </summary>
        /// <param name="rFC">Valor inicial de la propiedad RFC.</param>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static I_RFC1 CreateI_RFC1(global::System.String rFC, global::System.Int64 id)
        {
            I_RFC1 i_RFC1 = new I_RFC1();
            i_RFC1.RFC = rFC;
            i_RFC1.ID = id;
            return i_RFC1;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RFC
        {
            get
            {
                return _RFC;
            }
            set
            {
                OnRFCChanging(value);
                ReportPropertyChanging("RFC");
                _RFC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RFC");
                OnRFCChanged();
            }
        }
        private global::System.String _RFC;
        partial void OnRFCChanging(global::System.String value);
        partial void OnRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SNCF
        {
            get
            {
                return _SNCF;
            }
            set
            {
                OnSNCFChanging(value);
                ReportPropertyChanging("SNCF");
                _SNCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SNCF");
                OnSNCFChanged();
            }
        }
        private global::System.String _SNCF;
        partial void OnSNCFChanging(global::System.String value);
        partial void OnSNCFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUBCONTRATACION
        {
            get
            {
                return _SUBCONTRATACION;
            }
            set
            {
                OnSUBCONTRATACIONChanging(value);
                ReportPropertyChanging("SUBCONTRATACION");
                _SUBCONTRATACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUBCONTRATACION");
                OnSUBCONTRATACIONChanged();
            }
        }
        private global::System.String _SUBCONTRATACION;
        partial void OnSUBCONTRATACIONChanging(global::System.String value);
        partial void OnSUBCONTRATACIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="LCO_ACTUAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LCO_ACTUAL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LCO_ACTUAL.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static LCO_ACTUAL CreateLCO_ACTUAL(global::System.Int32 id)
        {
            LCO_ACTUAL lCO_ACTUAL = new LCO_ACTUAL();
            lCO_ACTUAL.ID = id;
            return lCO_ACTUAL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaUltimaActualizacion
        {
            get
            {
                return _FechaUltimaActualizacion;
            }
            set
            {
                OnFechaUltimaActualizacionChanging(value);
                ReportPropertyChanging("FechaUltimaActualizacion");
                _FechaUltimaActualizacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaUltimaActualizacion");
                OnFechaUltimaActualizacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaUltimaActualizacion;
        partial void OnFechaUltimaActualizacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaUltimaActualizacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreTabla
        {
            get
            {
                return _NombreTabla;
            }
            set
            {
                OnNombreTablaChanging(value);
                ReportPropertyChanging("NombreTabla");
                _NombreTabla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreTabla");
                OnNombreTablaChanged();
            }
        }
        private global::System.String _NombreTabla;
        partial void OnNombreTablaChanging(global::System.String value);
        partial void OnNombreTablaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="LCO0")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LCO0 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LCO0.
        /// </summary>
        /// <param name="idRfcLco">Valor inicial de la propiedad IdRfcLco.</param>
        /// <param name="rfc">Valor inicial de la propiedad Rfc.</param>
        /// <param name="noCertificado">Valor inicial de la propiedad noCertificado.</param>
        public static LCO0 CreateLCO0(global::System.Int64 idRfcLco, global::System.String rfc, global::System.String noCertificado)
        {
            LCO0 lCO0 = new LCO0();
            lCO0.IdRfcLco = idRfcLco;
            lCO0.Rfc = rfc;
            lCO0.noCertificado = noCertificado;
            return lCO0;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdRfcLco
        {
            get
            {
                return _IdRfcLco;
            }
            set
            {
                if (_IdRfcLco != value)
                {
                    OnIdRfcLcoChanging(value);
                    ReportPropertyChanging("IdRfcLco");
                    _IdRfcLco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRfcLco");
                    OnIdRfcLcoChanged();
                }
            }
        }
        private global::System.Int64 _IdRfcLco;
        partial void OnIdRfcLcoChanging(global::System.Int64 value);
        partial void OnIdRfcLcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rfc
        {
            get
            {
                return _Rfc;
            }
            set
            {
                OnRfcChanging(value);
                ReportPropertyChanging("Rfc");
                _Rfc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rfc");
                OnRfcChanged();
            }
        }
        private global::System.String _Rfc;
        partial void OnRfcChanging(global::System.String value);
        partial void OnRfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidezObligaciones
        {
            get
            {
                return _ValidezObligaciones;
            }
            set
            {
                OnValidezObligacionesChanging(value);
                ReportPropertyChanging("ValidezObligaciones");
                _ValidezObligaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidezObligaciones");
                OnValidezObligacionesChanged();
            }
        }
        private global::System.String _ValidezObligaciones;
        partial void OnValidezObligacionesChanging(global::System.String value);
        partial void OnValidezObligacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusCertificado
        {
            get
            {
                return _EstatusCertificado;
            }
            set
            {
                OnEstatusCertificadoChanging(value);
                ReportPropertyChanging("EstatusCertificado");
                _EstatusCertificado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusCertificado");
                OnEstatusCertificadoChanged();
            }
        }
        private global::System.String _EstatusCertificado;
        partial void OnEstatusCertificadoChanging(global::System.String value);
        partial void OnEstatusCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String noCertificado
        {
            get
            {
                return _noCertificado;
            }
            set
            {
                OnnoCertificadoChanging(value);
                ReportPropertyChanging("noCertificado");
                _noCertificado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("noCertificado");
                OnnoCertificadoChanged();
            }
        }
        private global::System.String _noCertificado;
        partial void OnnoCertificadoChanging(global::System.String value);
        partial void OnnoCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinal
        {
            get
            {
                return _FechaFinal;
            }
            set
            {
                OnFechaFinalChanging(value);
                ReportPropertyChanging("FechaFinal");
                _FechaFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinal");
                OnFechaFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinal;
        partial void OnFechaFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="LCO1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LCO1 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LCO1.
        /// </summary>
        /// <param name="idRfcLco">Valor inicial de la propiedad IdRfcLco.</param>
        /// <param name="rfc">Valor inicial de la propiedad Rfc.</param>
        /// <param name="noCertificado">Valor inicial de la propiedad noCertificado.</param>
        public static LCO1 CreateLCO1(global::System.Int64 idRfcLco, global::System.String rfc, global::System.String noCertificado)
        {
            LCO1 lCO1 = new LCO1();
            lCO1.IdRfcLco = idRfcLco;
            lCO1.Rfc = rfc;
            lCO1.noCertificado = noCertificado;
            return lCO1;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdRfcLco
        {
            get
            {
                return _IdRfcLco;
            }
            set
            {
                if (_IdRfcLco != value)
                {
                    OnIdRfcLcoChanging(value);
                    ReportPropertyChanging("IdRfcLco");
                    _IdRfcLco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRfcLco");
                    OnIdRfcLcoChanged();
                }
            }
        }
        private global::System.Int64 _IdRfcLco;
        partial void OnIdRfcLcoChanging(global::System.Int64 value);
        partial void OnIdRfcLcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rfc
        {
            get
            {
                return _Rfc;
            }
            set
            {
                OnRfcChanging(value);
                ReportPropertyChanging("Rfc");
                _Rfc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rfc");
                OnRfcChanged();
            }
        }
        private global::System.String _Rfc;
        partial void OnRfcChanging(global::System.String value);
        partial void OnRfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidezObligaciones
        {
            get
            {
                return _ValidezObligaciones;
            }
            set
            {
                OnValidezObligacionesChanging(value);
                ReportPropertyChanging("ValidezObligaciones");
                _ValidezObligaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidezObligaciones");
                OnValidezObligacionesChanged();
            }
        }
        private global::System.String _ValidezObligaciones;
        partial void OnValidezObligacionesChanging(global::System.String value);
        partial void OnValidezObligacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusCertificado
        {
            get
            {
                return _EstatusCertificado;
            }
            set
            {
                OnEstatusCertificadoChanging(value);
                ReportPropertyChanging("EstatusCertificado");
                _EstatusCertificado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusCertificado");
                OnEstatusCertificadoChanged();
            }
        }
        private global::System.String _EstatusCertificado;
        partial void OnEstatusCertificadoChanging(global::System.String value);
        partial void OnEstatusCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String noCertificado
        {
            get
            {
                return _noCertificado;
            }
            set
            {
                OnnoCertificadoChanging(value);
                ReportPropertyChanging("noCertificado");
                _noCertificado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("noCertificado");
                OnnoCertificadoChanged();
            }
        }
        private global::System.String _noCertificado;
        partial void OnnoCertificadoChanging(global::System.String value);
        partial void OnnoCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinal
        {
            get
            {
                return _FechaFinal;
            }
            set
            {
                OnFechaFinalChanging(value);
                ReportPropertyChanging("FechaFinal");
                _FechaFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinal");
                OnFechaFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinal;
        partial void OnFechaFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="LogI_RFC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogI_RFC : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LogI_RFC.
        /// </summary>
        /// <param name="idLogRFC">Valor inicial de la propiedad IdLogRFC.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="noRegistros">Valor inicial de la propiedad NoRegistros.</param>
        public static LogI_RFC CreateLogI_RFC(global::System.Int32 idLogRFC, global::System.DateTime fecha, global::System.Int32 noRegistros)
        {
            LogI_RFC logI_RFC = new LogI_RFC();
            logI_RFC.IdLogRFC = idLogRFC;
            logI_RFC.Fecha = fecha;
            logI_RFC.NoRegistros = noRegistros;
            return logI_RFC;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdLogRFC
        {
            get
            {
                return _IdLogRFC;
            }
            set
            {
                if (_IdLogRFC != value)
                {
                    OnIdLogRFCChanging(value);
                    ReportPropertyChanging("IdLogRFC");
                    _IdLogRFC = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdLogRFC");
                    OnIdLogRFCChanged();
                }
            }
        }
        private global::System.Int32 _IdLogRFC;
        partial void OnIdLogRFCChanging(global::System.Int32 value);
        partial void OnIdLogRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoRegistros
        {
            get
            {
                return _NoRegistros;
            }
            set
            {
                OnNoRegistrosChanging(value);
                ReportPropertyChanging("NoRegistros");
                _NoRegistros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoRegistros");
                OnNoRegistrosChanged();
            }
        }
        private global::System.Int32 _NoRegistros;
        partial void OnNoRegistrosChanging(global::System.Int32 value);
        partial void OnNoRegistrosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Error
        {
            get
            {
                return _Error;
            }
            set
            {
                OnErrorChanging(value);
                ReportPropertyChanging("Error");
                _Error = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Error");
                OnErrorChanged();
            }
        }
        private global::System.String _Error;
        partial void OnErrorChanging(global::System.String value);
        partial void OnErrorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tabla
        {
            get
            {
                return _Tabla;
            }
            set
            {
                OnTablaChanging(value);
                ReportPropertyChanging("Tabla");
                _Tabla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tabla");
                OnTablaChanged();
            }
        }
        private global::System.String _Tabla;
        partial void OnTablaChanging(global::System.String value);
        partial void OnTablaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="LogLCO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogLCO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LogLCO.
        /// </summary>
        /// <param name="idLogRFC">Valor inicial de la propiedad IdLogRFC.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="noRegistros">Valor inicial de la propiedad NoRegistros.</param>
        public static LogLCO CreateLogLCO(global::System.Int32 idLogRFC, global::System.DateTime fecha, global::System.Int32 noRegistros)
        {
            LogLCO logLCO = new LogLCO();
            logLCO.IdLogRFC = idLogRFC;
            logLCO.Fecha = fecha;
            logLCO.NoRegistros = noRegistros;
            return logLCO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdLogRFC
        {
            get
            {
                return _IdLogRFC;
            }
            set
            {
                if (_IdLogRFC != value)
                {
                    OnIdLogRFCChanging(value);
                    ReportPropertyChanging("IdLogRFC");
                    _IdLogRFC = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdLogRFC");
                    OnIdLogRFCChanged();
                }
            }
        }
        private global::System.Int32 _IdLogRFC;
        partial void OnIdLogRFCChanging(global::System.Int32 value);
        partial void OnIdLogRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoRegistros
        {
            get
            {
                return _NoRegistros;
            }
            set
            {
                OnNoRegistrosChanging(value);
                ReportPropertyChanging("NoRegistros");
                _NoRegistros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoRegistros");
                OnNoRegistrosChanged();
            }
        }
        private global::System.Int32 _NoRegistros;
        partial void OnNoRegistrosChanging(global::System.Int32 value);
        partial void OnNoRegistrosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Error
        {
            get
            {
                return _Error;
            }
            set
            {
                OnErrorChanging(value);
                ReportPropertyChanging("Error");
                _Error = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Error");
                OnErrorChanged();
            }
        }
        private global::System.String _Error;
        partial void OnErrorChanging(global::System.String value);
        partial void OnErrorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tabla
        {
            get
            {
                return _Tabla;
            }
            set
            {
                OnTablaChanging(value);
                ReportPropertyChanging("Tabla");
                _Tabla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tabla");
                OnTablaChanged();
            }
        }
        private global::System.String _Tabla;
        partial void OnTablaChanging(global::System.String value);
        partial void OnTablaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="vI_RFC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vI_RFC : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vI_RFC.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="rFC">Valor inicial de la propiedad RFC.</param>
        public static vI_RFC CreatevI_RFC(global::System.Int64 id, global::System.String rFC)
        {
            vI_RFC vI_RFC = new vI_RFC();
            vI_RFC.ID = id;
            vI_RFC.RFC = rFC;
            return vI_RFC;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RFC
        {
            get
            {
                return _RFC;
            }
            set
            {
                if (_RFC != value)
                {
                    OnRFCChanging(value);
                    ReportPropertyChanging("RFC");
                    _RFC = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RFC");
                    OnRFCChanged();
                }
            }
        }
        private global::System.String _RFC;
        partial void OnRFCChanging(global::System.String value);
        partial void OnRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SNCF
        {
            get
            {
                return _SNCF;
            }
            set
            {
                OnSNCFChanging(value);
                ReportPropertyChanging("SNCF");
                _SNCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SNCF");
                OnSNCFChanged();
            }
        }
        private global::System.String _SNCF;
        partial void OnSNCFChanging(global::System.String value);
        partial void OnSNCFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUBCONTRATACION
        {
            get
            {
                return _SUBCONTRATACION;
            }
            set
            {
                OnSUBCONTRATACIONChanging(value);
                ReportPropertyChanging("SUBCONTRATACION");
                _SUBCONTRATACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUBCONTRATACION");
                OnSUBCONTRATACIONChanged();
            }
        }
        private global::System.String _SUBCONTRATACION;
        partial void OnSUBCONTRATACIONChanging(global::System.String value);
        partial void OnSUBCONTRATACIONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="vI_RFC_Carga")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vI_RFC_Carga : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vI_RFC_Carga.
        /// </summary>
        /// <param name="rFC">Valor inicial de la propiedad RFC.</param>
        public static vI_RFC_Carga CreatevI_RFC_Carga(global::System.String rFC)
        {
            vI_RFC_Carga vI_RFC_Carga = new vI_RFC_Carga();
            vI_RFC_Carga.RFC = rFC;
            return vI_RFC_Carga;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RFC
        {
            get
            {
                return _RFC;
            }
            set
            {
                if (_RFC != value)
                {
                    OnRFCChanging(value);
                    ReportPropertyChanging("RFC");
                    _RFC = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RFC");
                    OnRFCChanged();
                }
            }
        }
        private global::System.String _RFC;
        partial void OnRFCChanging(global::System.String value);
        partial void OnRFCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SNCF
        {
            get
            {
                return _SNCF;
            }
            set
            {
                OnSNCFChanging(value);
                ReportPropertyChanging("SNCF");
                _SNCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SNCF");
                OnSNCFChanged();
            }
        }
        private global::System.String _SNCF;
        partial void OnSNCFChanging(global::System.String value);
        partial void OnSNCFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUBCONTRATACION
        {
            get
            {
                return _SUBCONTRATACION;
            }
            set
            {
                OnSUBCONTRATACIONChanging(value);
                ReportPropertyChanging("SUBCONTRATACION");
                _SUBCONTRATACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUBCONTRATACION");
                OnSUBCONTRATACIONChanged();
            }
        }
        private global::System.String _SUBCONTRATACION;
        partial void OnSUBCONTRATACIONChanging(global::System.String value);
        partial void OnSUBCONTRATACIONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="vLCO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vLCO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vLCO.
        /// </summary>
        /// <param name="idRfcLco">Valor inicial de la propiedad IdRfcLco.</param>
        /// <param name="rfc">Valor inicial de la propiedad Rfc.</param>
        /// <param name="noCertificado">Valor inicial de la propiedad noCertificado.</param>
        public static vLCO CreatevLCO(global::System.Int64 idRfcLco, global::System.String rfc, global::System.String noCertificado)
        {
            vLCO vLCO = new vLCO();
            vLCO.IdRfcLco = idRfcLco;
            vLCO.Rfc = rfc;
            vLCO.noCertificado = noCertificado;
            return vLCO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdRfcLco
        {
            get
            {
                return _IdRfcLco;
            }
            set
            {
                if (_IdRfcLco != value)
                {
                    OnIdRfcLcoChanging(value);
                    ReportPropertyChanging("IdRfcLco");
                    _IdRfcLco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRfcLco");
                    OnIdRfcLcoChanged();
                }
            }
        }
        private global::System.Int64 _IdRfcLco;
        partial void OnIdRfcLcoChanging(global::System.Int64 value);
        partial void OnIdRfcLcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rfc
        {
            get
            {
                return _Rfc;
            }
            set
            {
                if (_Rfc != value)
                {
                    OnRfcChanging(value);
                    ReportPropertyChanging("Rfc");
                    _Rfc = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Rfc");
                    OnRfcChanged();
                }
            }
        }
        private global::System.String _Rfc;
        partial void OnRfcChanging(global::System.String value);
        partial void OnRfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidezObligaciones
        {
            get
            {
                return _ValidezObligaciones;
            }
            set
            {
                OnValidezObligacionesChanging(value);
                ReportPropertyChanging("ValidezObligaciones");
                _ValidezObligaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidezObligaciones");
                OnValidezObligacionesChanged();
            }
        }
        private global::System.String _ValidezObligaciones;
        partial void OnValidezObligacionesChanging(global::System.String value);
        partial void OnValidezObligacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusCertificado
        {
            get
            {
                return _EstatusCertificado;
            }
            set
            {
                OnEstatusCertificadoChanging(value);
                ReportPropertyChanging("EstatusCertificado");
                _EstatusCertificado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusCertificado");
                OnEstatusCertificadoChanged();
            }
        }
        private global::System.String _EstatusCertificado;
        partial void OnEstatusCertificadoChanging(global::System.String value);
        partial void OnEstatusCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String noCertificado
        {
            get
            {
                return _noCertificado;
            }
            set
            {
                if (_noCertificado != value)
                {
                    OnnoCertificadoChanging(value);
                    ReportPropertyChanging("noCertificado");
                    _noCertificado = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("noCertificado");
                    OnnoCertificadoChanged();
                }
            }
        }
        private global::System.String _noCertificado;
        partial void OnnoCertificadoChanging(global::System.String value);
        partial void OnnoCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinal
        {
            get
            {
                return _FechaFinal;
            }
            set
            {
                OnFechaFinalChanging(value);
                ReportPropertyChanging("FechaFinal");
                _FechaFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinal");
                OnFechaFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinal;
        partial void OnFechaFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DescargasSatModel", Name="vLCO_Carga")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vLCO_Carga : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vLCO_Carga.
        /// </summary>
        /// <param name="rfc">Valor inicial de la propiedad Rfc.</param>
        /// <param name="noCertificado">Valor inicial de la propiedad noCertificado.</param>
        public static vLCO_Carga CreatevLCO_Carga(global::System.String rfc, global::System.String noCertificado)
        {
            vLCO_Carga vLCO_Carga = new vLCO_Carga();
            vLCO_Carga.Rfc = rfc;
            vLCO_Carga.noCertificado = noCertificado;
            return vLCO_Carga;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rfc
        {
            get
            {
                return _Rfc;
            }
            set
            {
                if (_Rfc != value)
                {
                    OnRfcChanging(value);
                    ReportPropertyChanging("Rfc");
                    _Rfc = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Rfc");
                    OnRfcChanged();
                }
            }
        }
        private global::System.String _Rfc;
        partial void OnRfcChanging(global::System.String value);
        partial void OnRfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidezObligaciones
        {
            get
            {
                return _ValidezObligaciones;
            }
            set
            {
                OnValidezObligacionesChanging(value);
                ReportPropertyChanging("ValidezObligaciones");
                _ValidezObligaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidezObligaciones");
                OnValidezObligacionesChanged();
            }
        }
        private global::System.String _ValidezObligaciones;
        partial void OnValidezObligacionesChanging(global::System.String value);
        partial void OnValidezObligacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusCertificado
        {
            get
            {
                return _EstatusCertificado;
            }
            set
            {
                OnEstatusCertificadoChanging(value);
                ReportPropertyChanging("EstatusCertificado");
                _EstatusCertificado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusCertificado");
                OnEstatusCertificadoChanged();
            }
        }
        private global::System.String _EstatusCertificado;
        partial void OnEstatusCertificadoChanging(global::System.String value);
        partial void OnEstatusCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String noCertificado
        {
            get
            {
                return _noCertificado;
            }
            set
            {
                if (_noCertificado != value)
                {
                    OnnoCertificadoChanging(value);
                    ReportPropertyChanging("noCertificado");
                    _noCertificado = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("noCertificado");
                    OnnoCertificadoChanged();
                }
            }
        }
        private global::System.String _noCertificado;
        partial void OnnoCertificadoChanging(global::System.String value);
        partial void OnnoCertificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinal
        {
            get
            {
                return _FechaFinal;
            }
            set
            {
                OnFechaFinalChanging(value);
                ReportPropertyChanging("FechaFinal");
                _FechaFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinal");
                OnFechaFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinal;
        partial void OnFechaFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();

        #endregion

    
    }

    #endregion

    
}
